#!/usr/bin/env python3
"""Export every PowerPoint lecture for the site and the gates. Needs Windows and PowerPoint.

A week's lecture may be a PowerPoint deck, lectures-and-labs/weekNN/<topic>-lecture.pptx,
instead of a Marp deck (<topic>-lecture.md). CI runs on Linux and cannot open a deck,
so this script writes two files beside it, to be committed with it:

  <topic>-lecture.pdf       the slides as PowerPoint itself prints them (its fonts,
                            code colours and diagrams); the site shows this PDF.
  <topic>-lecture.notes.md  every slide's text and speaker notes in the shape of a
                            Marp deck, so the snippet, notes and portability gates
                            read it, the site prints it under the PDF, and a student's
                            assistant can read the lecture. Generated: never edit it.

The text copy's frontmatter records the SHA-256 of the deck, of the PDF and of its
own text, and check_schedule.py fails when any of them stops matching: a deck saved
since its export, a PDF from another export, a text copy edited by hand.

A code box says what it holds in its alt text, "Code, python" (the powerpoint-maker
skill writes it). Add ", no-parse" (right-click the box, View Alt Text) to exempt a
deliberately incomplete snippet from verify_snippets.py, as <!-- no-parse --> above
a fence does in a Marp deck.

Before writing anything it renders each slide's markdown as the site will and
checks that the slide's words came through and no markup shows as text.

Usage, from the repo root, with the deck closed (PowerPoint locks a deck it has open):
    python scripts/export_decks.py            # every deck whose exports are stale
    python scripts/export_decks.py --force    # every PowerPoint deck
Needs pywin32, python-pptx and markdown-it-py (pip install pywin32 python-pptx markdown-it-py).
"""
from __future__ import annotations

import argparse
import hashlib
import html
import io
import json
import re
import shutil
import sys
import tempfile
from itertools import groupby
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from schedule import Row, load, sha256, stale_exports  # noqa: E402

A = "{http://schemas.openxmlformats.org/drawingml/2006/main}"
P = "{http://schemas.openxmlformats.org/presentationml/2006/main}"
MONO_FONTS = {"Consolas", "Cascadia Code", "Cascadia Mono", "Courier New", "Lucida Console"}
GENERATED = ("<!-- Generated by scripts/export_decks.py from {deck}. Do not edit this file: "
             "edit the deck in PowerPoint, then run the script again. -->")


# --------------------------------------------------------------------------
# The PDF, printed by PowerPoint
# --------------------------------------------------------------------------

class PowerPoint:
    """PowerPoint over COM. It is started only when it is not already running,
    and quit only when this script started it and nothing is open in it: the
    lecturer may have PowerPoint open with other work."""

    def __enter__(self) -> "PowerPoint":
        try:
            import pythoncom
            import win32com.client
        except ImportError:
            raise SystemExit("export_decks: needs Windows, PowerPoint and pywin32 "
                             "(pip install pywin32)")
        pythoncom.CoInitialize()
        try:
            self.app = win32com.client.GetActiveObject("PowerPoint.Application")
            self.started = False
        except Exception:                      # not running
            self.app = win32com.client.Dispatch("PowerPoint.Application")
            self.started = True
        self.alerts = self.app.DisplayAlerts
        self.app.DisplayAlerts = 1             # ppAlertsNone: no dialog may block the export
        return self

    def export_pdf(self, deck: Path, pdf: Path) -> None:
        # Read-only, untitled (so it never joins the recent-files list), no window.
        pres = self.app.Presentations.Open(str(deck), True, True, False)
        try:
            # PDF, print quality, slides only, hidden slides left out, tagged for
            # screen readers, with the title in its properties. PrintRange must be
            # passed as None: pywin32 cannot fill in that optional object itself.
            pres.ExportAsFixedFormat(str(pdf), 2, Intent=2, FrameSlides=0, OutputType=1,
                                     PrintHiddenSlides=0, PrintRange=None, RangeType=1,
                                     IncludeDocProperties=True, DocStructureTags=True,
                                     BitmapMissingFonts=True, UseISO19005_1=False)
        finally:
            pres.Close()

    def __exit__(self, *exc) -> None:
        self.app.DisplayAlerts = self.alerts
        if self.started and self.app.Presentations.Count == 0 and not self.app.Visible:
            self.app.Quit()


# --------------------------------------------------------------------------
# The text copy
# --------------------------------------------------------------------------

def escape(text: str) -> str:
    """Slide text as literal markdown: no emphasis, code or HTML it did not have."""
    text = text.replace("\\", "\\\\").replace("*", "\\*").replace("`", "\\`")
    text = re.sub(r"(?<![A-Za-z0-9])_|_(?![A-Za-z0-9])", r"\\_", text)
    return re.sub(r"<(?=[A-Za-z/!?])", "&lt;", text)


def escape_start(line: str) -> str:
    """Stop a paragraph that starts like a heading, list, quote or rule from becoming one."""
    if re.match(r"#{1,6}\s|>|[-+*]\s|(-{3,}|\*{3,}|_{3,}|=+)\s*$", line):
        return "\\" + line
    m = re.match(r"\d+(?=[.)]\s)", line)
    return line[:m.end()] + "\\" + line[m.end():] if m else line


def code_span(text: str) -> str:
    ticks = "`"
    while ticks in text:
        ticks += "`"
    pad = " " if text.startswith("`") or text.endswith("`") else ""
    return f"{ticks}{pad}{text}{pad}{ticks}"


def wrap(marks: str, text: str) -> str:
    """`marks` around text, whitespace kept outside: `** x**` is not bold in markdown."""
    core = text.strip()
    if not marks or not core:
        return text
    return f"{text[:len(text) - len(text.lstrip())]}{marks}{core}{marks}{text[len(text.rstrip()):]}"


def line_markdown(runs: list[tuple]) -> str:
    """One line of (text, bold, italic, mono, link) runs as markdown. Emphasis
    NESTS rather than being set run by run: bold, then bold italic, then bold
    again must come out as **a *b* c**, because **a** ***b***** c** leaves a
    run of five asterisks that markdown cannot pair and prints."""
    out = []
    for link, same_link in groupby(runs, key=lambda r: r[4]):
        text = ""
        for bold, same_bold in groupby(same_link, key=lambda r: r[1]):
            inner = ""
            for italic, same in groupby(same_bold, key=lambda r: r[2]):
                inner += wrap("*" if italic else "",
                              "".join(code_run(t) if mono else escape(t)
                                      for t, _, _, mono, _ in same))
            text += wrap("**" if bold else "", inner)
        out.append(f"[{text.strip()}]({link})" if link else text)
    return "".join(out)


def code_run(text: str) -> str:
    """A monospace run as a code span, its outer spaces left outside the backticks."""
    if not text.strip():
        return text
    return (text[:len(text) - len(text.lstrip())] + code_span(text.strip())
            + text[len(text.rstrip()):])


def inline(paragraph) -> str:
    """A paragraph's runs as inline markdown: **bold**, *italic*, `code`, links.
    A line break inside the paragraph comes back as a newline."""
    from pptx.text.text import _Run
    lines: list[list[tuple]] = [[]]
    for el in paragraph._p:
        if el.tag == A + "r":
            run = _Run(el, paragraph)
            link = run.hyperlink.address if el.find(f"{A}rPr/{A}hlinkClick") is not None else None
            lines[-1].append((run.text, bool(run.font.bold), bool(run.font.italic),
                              run.font.name in MONO_FONTS, link))
        elif el.tag == A + "br":
            lines.append([])
        elif el.tag == A + "fld":
            lines[-1].append(("".join(t.text or "" for t in el.iter(A + "t")),
                              False, False, False, None))
    return "\n".join(line_markdown(runs).strip() for runs in lines).strip()


def cnvpr(shape):
    return shape._element.find(f".//{P}cNvPr")


def layout_list_style(shape, slide):
    """A placeholder's list style as its layout defines it, or None."""
    if not shape.is_placeholder:
        return None
    base = slide.slide_layout.placeholders.get(idx=shape.placeholder_format.idx)
    return base._element.find(f".//{A}lstStyle") if base is not None else None


def list_styles(shape, slide) -> list:
    """Where a paragraph's bullet setting is inherited from: the shape's own
    list style, then (for a placeholder) its layout placeholder's."""
    styles = [shape._element.find(f".//{A}lstStyle"), layout_list_style(shape, slide)]
    return [s for s in styles if s is not None]


def bullet_setting(ppr) -> bool | None:
    if ppr is None:
        return None
    if ppr.find(A + "buNone") is not None:
        return False
    if ppr.find(A + "buChar") is not None or ppr.find(A + "buAutoNum") is not None:
        return True
    return None


def is_bullet(paragraph, shape, slide) -> bool:
    setting = bullet_setting(paragraph._p.find(A + "pPr"))
    for style in list_styles(shape, slide):
        if setting is None:
            setting = bullet_setting(style.find(f"{A}lvl{paragraph.level + 1}pPr"))
    if setting is not None:
        return setting
    # Otherwise the master decides: body and content placeholders are bulleted.
    return shape.is_placeholder and shape.placeholder_format.type in (2, 7)   # BODY, OBJECT


def is_heading(shape, slide) -> bool:
    """A placeholder its layout sets bold and unbulleted, e.g. a Comparison
    slide's column headings."""
    style = layout_list_style(shape, slide)
    lvl1 = style.find(A + "lvl1pPr") if style is not None else None
    if lvl1 is None or lvl1.find(A + "buNone") is None:
        return False
    rpr = lvl1.find(A + "defRPr")
    return rpr is not None and rpr.get("b") in ("1", "true")


def text_blocks(shape, slide) -> list[str]:
    heading = is_heading(shape, slide)
    blocks, items = [], []
    for paragraph in shape.text_frame.paragraphs:
        md = inline(paragraph)
        if not md:
            continue
        if heading:
            blocks.append("### " + md.replace("\n", " "))
        elif is_bullet(paragraph, shape, slide):
            indent = "  " * paragraph.level
            items.append(f"{indent}- " + escape_start(md).replace("\n", f"\\\n{indent}  "))
            continue
        else:
            blocks.append(escape_start(md).replace("\n", "\\\n"))
        if items:                              # a list ends where anything else starts
            blocks.insert(len(blocks) - 1, "\n".join(items))
            items = []
    if items:
        blocks.append("\n".join(items))
    return blocks


def code_block(shape) -> str:
    """A code box as a fence, its language (and any no-parse) from its alt text."""
    words = [w.strip().lower() for w in (cnvpr(shape).get("descr") or "").split(",")]
    lang = words[1] if len(words) > 1 and words[1] else "text"
    lang = "text" if lang == "plain text" else re.sub(r"[^a-z0-9_+-]", "", lang)
    lines = []
    for paragraph in shape.text_frame.paragraphs:
        line = "".join("\n" if el.tag == A + "br" else "".join(t.text or "" for t in el.iter(A + "t"))
                       for el in paragraph._p if el.tag in (A + "r", A + "br", A + "fld"))
        lines.append(line.rstrip())
    while lines and not lines[-1]:
        lines.pop()
    code = "\n".join(lines)
    fence = "```"
    while fence in code:
        fence += "`"
    block = f"{fence}{lang}\n{code}\n{fence}"
    return ("<!-- no-parse -->\n" + block) if "no-parse" in words[2:] else block


def diagram_block(group, slide) -> str:
    """A flow as a numbered list, left to right; a stack as a list, top to bottom.
    A stack's items take `+`, not `-`: in CommonMark two `-` lists with only a
    blank line between them are ONE list, and the slide's bullets often follow."""
    boxes = [s for s in group.shapes if s.has_text_frame and s.text_frame.text.strip()]
    if group.name.startswith("Flow"):
        items = []
        for n, box in enumerate(sorted(boxes, key=lambda s: s.left), 1):
            paras = [inline(p) for p in box.text_frame.paragraphs if inline(p)]
            if len(paras) > 1 and re.fullmatch(r"\**\d{1,2}\**", paras[0]):
                paras = paras[1:]              # the step number the box prints
            items.append(f"{n}. " + escape_start(" ".join(paras)).replace("\n", " "))
        return "\n".join(items)
    items = []
    for box in sorted(boxes, key=lambda s: s.top):
        md = " ".join(inline(p) for p in box.text_frame.paragraphs if inline(p)).replace("\n", " ")
        text, _, label = md.partition("\t")
        label = label.strip().strip("*").strip()
        items.append("+ " + escape_start(text.strip()) + (f" · *{label}*" if label else ""))
    return "\n".join(items)


def table_block(shape) -> str:
    def cell(c):
        return " ".join(inline(p) for p in c.text_frame.paragraphs).replace("|", "\\|").replace("\n", " ")
    rows = [[cell(c) for c in row.cells] for row in shape.table.rows]
    lines = ["| " + " | ".join(rows[0]) + " |", "|" + "---|" * len(rows[0])]
    return "\n".join(lines + ["| " + " | ".join(r) + " |" for r in rows[1:]])


def shape_blocks(shape, slide, warnings: list[str], where: str) -> list[str]:
    descr = (cnvpr(shape).get("descr") or "").strip() if cnvpr(shape) is not None else ""
    if shape.shape_type == 6:                  # a group
        if shape.name.startswith(("Flow", "Stack")):
            return [diagram_block(shape, slide)]
        return [b for s in shape.shapes for b in shape_blocks(s, slide, warnings, where)]
    if descr.lower().startswith("code") and shape.has_text_frame:
        return [code_block(shape)]
    if getattr(shape, "has_table", False) and shape.has_table:
        return [table_block(shape)]
    if shape.has_text_frame:
        return text_blocks(shape, slide)
    if shape.shape_type == 13:                 # a picture
        return [f"*\\[Picture: {escape(descr)}\\]*" if descr else "*\\[Picture\\]*"]
    if getattr(shape, "has_chart", False) and shape.has_chart:
        return [f"*\\[Chart: {escape(descr)}\\]*" if descr else "*\\[Chart\\]*"]
    if shape._element.tag == P + "graphicFrame":
        warnings.append(f"{where}: a SmartArt or other object's text is not in the text copy")
        return [f"*\\[Diagram: {escape(descr)}\\]*" if descr else "*\\[Diagram\\]*"]
    return []


def slides_of(deck_bytes: bytes, warnings: list[str]) -> tuple[str, list[tuple[str, str]]]:
    """The deck's title, and each slide shown (hidden ones are not in the PDF
    either) as (markdown, speaker notes)."""
    from pptx import Presentation
    prs = Presentation(io.BytesIO(deck_bytes))
    title, out = "", []
    for slide in prs.slides:
        if slide._element.get("show") == "0":
            continue
        where = f"slide {len(out) + 1}"
        head = slide.shapes.title
        blocks = []
        if head is not None and head.text_frame.text.strip():
            text = " ".join(inline(p) for p in head.text_frame.paragraphs if inline(p)).replace("\n", " ")
            blocks.append(("#" if not out else "##") + " " + text)
            title = title or head.text_frame.text.replace("\v", " ").replace("\n", " ").strip()
        for shape in slide.shapes:
            if head is None or shape.shape_id != head.shape_id:
                blocks += shape_blocks(shape, slide, warnings, where)
        notes = ""
        if slide.has_notes_slide and slide.notes_slide.notes_text_frame is not None:
            notes = slide.notes_slide.notes_text_frame.text.replace("\v", "\n").strip()
            notes = re.sub(r"\n{3,}", "\n\n", notes)
        if "-->" in notes or re.search(r"(?m)^---\s*$", notes):
            raise SystemExit(f"export_decks: {where}: its speaker notes hold '-->' or a '---' "
                             f"line, which would break the text copy; reword that")
        if not notes:
            warnings.append(f"{where}: no speaker notes (check_speaker_notes.py will fail)")
        out.append(("\n\n".join(blocks), notes))
    return title or prs.core_properties.title, out


def deck_texts(deck_bytes: bytes) -> list[str]:
    """Each shown slide's text as the deck holds it, for round_trip()."""
    from pptx import Presentation
    out = []
    for slide in Presentation(io.BytesIO(deck_bytes)).slides:
        if slide._element.get("show") == "0":
            continue
        texts = []

        def walk(shapes):
            for sh in shapes:
                if sh.shape_type == 6:
                    walk(sh.shapes)
                elif sh.has_text_frame:
                    for p in sh.text_frame.paragraphs:
                        text = "".join(r.text for r in p.runs)
                        if not (sh.name.startswith("Step") and re.fullmatch(r"\s*\d{1,2}\s*", text)):
                            texts.append(text)
                elif getattr(sh, "has_table", False) and sh.has_table:
                    texts.extend(c.text for row in sh.table.rows for c in row.cells)
        walk(slide.shapes)
        out.append(" ".join(texts))
    return out


def round_trip(deck_bytes: bytes, slides: list[tuple[str, str]]) -> list[str]:
    """Render each slide's markdown as the site will (markdown-it) and compare
    its words with the deck's: nothing lost, nothing added, and no `*` or
    backtick left over, which is markup that failed to parse."""
    from build_lab_pages import RENDERER
    problems = []
    for n, (source, (md, _)) in enumerate(zip(deck_texts(deck_bytes), slides), 1):
        shown = html.unescape(re.sub(r"<[^>]+>", " ", RENDERER.render(
            re.sub(r"<!--.*?-->", "", md, flags=re.S))))
        if re.findall(r"\w+", shown) != re.findall(r"\w+", source):
            problems.append(f"slide {n}: its words do not survive the conversion")
        for mark in "*`":
            if shown.count(mark) != source.count(mark):
                problems.append(f"slide {n}: a {mark!r} shows as text, so some markup did not parse")
    return problems


def text_copy(row: Row, title: str, slides: list[tuple[str, str]], deck_sha: str, pdf_sha: str) -> str:
    parts = []
    for md, notes in slides:
        note = f"<!-- Speaker notes: {notes} -->" if notes else ""
        parts.append("\n\n".join(x for x in (note, md) if x))
    body = ("\n" + GENERATED.format(deck=row.lecture.name) + "\n\n"
            + "\n\n---\n\n".join(parts) + "\n")
    head = ["---",
            f"title: {json.dumps(title, ensure_ascii=False)}",
            f"topic: {row.deck}",
            "type: lecture",
            "source: authored",
            f"deck: {row.lecture.name}",
            f"deck-sha256: {deck_sha}",
            f"pdf-sha256: {pdf_sha}",
            f"text-sha256: {hashlib.sha256(body.encode('utf-8')).hexdigest()}",
            "---"]
    return "\n".join(head) + "\n" + body


# --------------------------------------------------------------------------

def export(row: Row, app: PowerPoint) -> None:
    try:
        deck_bytes = row.lecture.read_bytes()
    except PermissionError:
        raise SystemExit(f"export_decks: {row.lecture.as_posix()} is locked; close it in "
                         f"PowerPoint and run this again")
    warnings: list[str] = []
    title, slides = slides_of(deck_bytes, warnings)
    broken = round_trip(deck_bytes, slides)
    if broken:
        raise SystemExit("export_decks: the text copy would not match the deck, so nothing "
                         "was written (a bug in this script; the deck is fine):\n  "
                         + "\n  ".join(broken))
    with tempfile.TemporaryDirectory() as tmp:
        # Export from a copy of exactly the bytes that were read and hashed, so the
        # PDF matches the recorded deck even if the file is saved meanwhile.
        copy, pdf = Path(tmp) / "deck.pptx", Path(tmp) / "deck.pdf"
        copy.write_bytes(deck_bytes)
        app.export_pdf(copy, pdf)
        shutil.copyfile(pdf, row.lecture_pdf)
    deck_sha = hashlib.sha256(deck_bytes).hexdigest()
    row.lecture_text.write_text(text_copy(row, title, slides, deck_sha, sha256(row.lecture_pdf)),
                                encoding="utf-8", newline="\n")
    codes = sum(len(re.findall(r"(?m)^`{3,}[a-z]", md)) for md, _ in slides)
    unparsed = sum(md.count("<!-- no-parse -->") for md, _ in slides)
    print(f"exported {row.lecture.as_posix()}: {len(slides)} slides, "
          f"{sum(bool(n) for _, n in slides)} with notes, {codes} code boxes "
          f"({unparsed} marked no-parse) -> "
          f"{row.lecture_pdf.name} ({row.lecture_pdf.stat().st_size:,} bytes), "
          f"{row.lecture_text.name}")
    for w in warnings:
        print(f"  warning: {w}")
    problems = stale_exports(row)
    if problems:
        raise SystemExit(f"export_decks: {row.lecture.as_posix()} still stale: {'; '.join(problems)}")


def main() -> None:
    for stream in (sys.stdout, sys.stderr):
        stream.reconfigure(encoding="utf-8", errors="replace")
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--force", action="store_true", help="export even when up to date")
    args = ap.parse_args()
    decks = [r for r in load().teaching if r.is_pptx]
    todo = [r for r in decks if args.force or stale_exports(r)]
    for r in decks:
        if r not in todo:
            print(f"up to date: {r.lecture.as_posix()}")
    if todo:
        with PowerPoint() as app:
            for r in todo:
                export(r, app)
    print(f"export_decks: {len(decks)} PowerPoint deck(s), {len(todo)} exported")


if __name__ == "__main__":
    main()
